# -*- coding: utf-8 -*-
"""Writing and reading files in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uu2WBVpOoQrxstfvvvu322dcx8MuVhNC
"""

pip install faker

import csv #Import the csv module to use its functionalities

output = open('myCSV.CSV',mode='w')
mywriter=csv.writer(output)
header=['name','age']
mywriter.writerow(header)
data=['Bob Smith',40]
mywriter.writerow(data)
output.close()
print(data)

"""Writing CSVs using the Python CSV Library"""

from faker import Faker
import csv

fake = Faker()
header = ['name', 'age', 'street', 'city', 'state', 'zip', 'lng', 'lat']

with open('data.csv', 'w', newline='') as output:
    mywriter = csv.writer(output)
    mywriter.writerow(header)
    for _ in range(1000):
        mywriter.writerow([fake.name(),fake.random_int(min=18, max=80, step=1),
            fake.street_address(),fake.city(),fake.state(), fake.zipcode(),
            fake.longitude(),fake.latitude()])

print("Data generation complete! File: data.csv")

import pandas as pd
# Read the CSV data into a Pandas DataFrame
df = pd.read_csv('data.csv')
print(df.head())  # Print the first few rows to inspect the data

"""Reading CSVs"""

import csv

with open('data.csv', newline='') as f:
    myreader = csv.DictReader(f)
    headers = myreader.fieldnames  # `next(myreader)` isn't needed with `DictReader`
    for row in myreader:
        print(row['name'])

"""Reading and writing CSVs using pandas DataFrames"""

#pip install pandas

import pandas as pd
df=pd.read_csv('data.csv') #(df=pd.read_csv()('data.CSV'))wrongly written oinn the book
df.head(10)

"""Create a DataFrame in Python"""

data={'Name':['Paul','Bob','Susan','Yolanda'],
'Age':[23,45,18,21]}
df=pd.DataFrame(data)
df.to_csv('fromdf.CSV',index=False)

import pandas as pd
df=pd.read_csv('fromdf.CSV') #(df=pd.read_csv()('data.CSV'))wrongly written oinn the book
df.head(10)