# -*- coding: utf-8 -*-
"""Writing JSON with Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTGPYtcbLg2CKjW1Xxo1VfDOxQYz7rpn

Writing JSON with Python
"""

pip install faker

from faker import Faker
import json

# Open the file in write mode ('w')
output = open('data.JSON', 'w')
fake = Faker()

alldata = {}
alldata['records'] = []

for x in range(1000):
    data = {"name": fake.name(), "age": fake.random_int(min=18, max=80, step=1),
            "street": fake.street_address(), "city": fake.city(),
            "state": fake.state(), "zip": fake.zipcode(),
            "lng": float(fake.longitude()), "lat": float(fake.latitude())}
    alldata['records'].append(data)

# Write the JSON data to the file
json.dump(alldata, output)

# Close the file to ensure data is written
output.close()  # Add this line to close the file

# Open the file in read mode ('r')
with open("data.JSON", "r") as f:
    data = json.load(f)
    print(data['records'][0])
    print(data['records'][0]['name'])

import pandas as pd
df=pd.read_json('data.JSON')
df.head(10)

#import pandas.io.json as pd_JSON
#f=open('data.JSON','r')
#data=pd_JSON.loads(f.read())
#df=pd_JSON.json_normalize(data,record_path='records')
#df.head(10)
#above code from book had an error
#The error message "AttributeError: module 'pandas.io.json' has no attribute 'json_normalize'" indicates that the function json_normalize is not available within the pandas.io.json module. This function was moved to the main pandas namespace in later versions of the pandas library
import pandas as pd
f = open('data.JSON', 'r')
data = pd.json_normalize(json.load(f)) # Use pd.json_normalize directly
f.close()
df = pd.DataFrame(data)
df.head(10)

df.head(2).to_json()

df.head(2).to_json(orient='records')